# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgileUs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgileUs
    pod 'MessageKit', '~> 3.3.0'
    pod 'InputBarAccessoryView', '5.1.0'
    pod 'Firebase/Analytics'
    pod 'Firebase/Storage'
    pod 'Charts'


  target 'AgileUsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AgileUsUITests' do
    # Pods for testing
  end

end
